// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import { Autocomplete } from "stimulus-autocomplete";

import OrderEquipamentController from "./order_equipament_controller";

application.register("autocomplete", Autocomplete);
application.register("order-equipament", OrderEquipamentController);
